# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Critique Gaming
email: office@critique-gaming.com
description: We're a video game development company, based in Bucharest, Romania, excited about producing socially responsible video games.

og_image: /images/og_image.jpg
og_image_width: 1200
og_image_height: 1200
og_type: website
fb_app_id: 1653261584986384
google_analytics_ua: UA-18276515-5

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://critique-gaming.com" # the base hostname & protocol for your site

twitter_username: Critique_Gaming
facebook_username:  CritiqueGaming

excerpt_separator: "<!--more-->"
nav_links:
  - title: Interrogation
    url: /interrogation
  - title: Blog
    url: /blog
  - title: About
    url: /#about
  - title: Contact
    url: /#contact
  - title: Press kit
    url: https://presskit.critique-gaming.com

# Build settings
markdown: kramdown
gems:
  - kramdown
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 2 versions
  - "ie >= 9"
  - "> 1%"

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'bin']
