# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Critique Gaming
email: office@critique-gaming.com
description: Critique Gaming is a video game development company, based in Bucharest, Romania, excited about producing socially responsible video games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://staging.critique-gaming.com" # the base hostname & protocol for your site
twitter_username: Critique_Gaming
facebook_username:  CritiqueGaming
og_image: /images/og_image.png
og_image_width: 1200
og_image_height: 1200
og_type: website
fb_app_id: 1653261584986384
nav_links:
  - title: Interrogation
    url: /interrogation
  - title: Blog
    url: /blog
  - title: About
    url: /#about
  - title: Contact
    url: /#contact
  - title: Press kit
    url: https://presskit.critique-gaming.com

# Build settings
markdown: kramdown
gems:
  - kramdown
  - jekyll-autoprefixer

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'bin']
